app:
  build: .
  command: npm run dev
  ports:
    - "3030:3030"
  volumes:
    - .:/app
  volumes_from:
    - node_modules

node_modules:
  image: busybox
  volumes:
    - node_modules:/node_modules
