app:
  build: .
  command: npm run dev
  ports:
    - "8080:8080"
  volumes:
    - .:/app
  volumes_from:
    - node_modules

node_modules:
  image: busybox
  volumes:
    - node_modules:/node_modules
